# Generated by Django 3.1.5 on 2021-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210124_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
