# Generated by Django 3.1.5 on 2021-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Others', max_length=64),
            preserve_default=False,
        ),
    ]
